version: '2'

services:
    db:
        image: mysql:5.7
#        restart: always
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_DATABASE}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

    php:
        build: php
#        restart: always
        links:
            - db
        working_dir: /var/www
        volumes:
            - ../www:/var/www

    nginx:
        image: nginx:latest
#        restart: always
        links:
            - php
        working_dir: /var/www
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../www:/var/www
        ports:
            - "{$APP_PORT}:80"
